// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:45a56df1-afc0-4de9-b033-c47c54238737",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xki6kJQ82",
    "aws_user_pools_web_client_id": "3vr4omqomk6a7lpgk0gumju8tg",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "snifsearchapi",
            "endpoint": "https://ap27bt5uh5.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "snif-store-prod",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d2hito639hswgr.cloudfront.net",
    "aws_user_files_s3_bucket": "snif-store-prodprod-prod",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
